name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: psf/black@stable
        with:
          src: "./data"
